---
language: ruby
rvm:
- 2.0.0
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    - atlrug-website@googlegroups.com
    on_success: change
    on_failure: always
env:
  global:
  - AR4_S_K_B=09ced0f5527b74049d122b000b36e7d5531584788dc2650ac0e8ade11d79668d8978ad725fe2c0dcba4f0f2cff7bba336fc726019def6b2dea969554c7deb2d8
  - secure: |-
      c0XZtT+1bSTo7cJliy5ADkNaBhT/qPyaZYKj5b76HuAThaS0pwjpUcQFiF2T
      np8OoejhuUOV7s3jqunxx9QFwoYkCipvrA/WwnUM1FsmfOwyIa3c8zm+xl1K
      GlG+N57HXynaiEKWWCTdjrVhCGlJxM6iAX9zA2BC+KHJAx8GPuE=
