---
language: ruby
rvm:
- 2.0.0
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
env:
  global:
  - AR4_S_K_B=09ced0f5527b74049d122b000b36e7d5531584788dc2650ac0e8ade11d79668d8978ad725fe2c0dcba4f0f2cff7bba336fc726019def6b2dea969554c7deb2d8
  - secure: |-
      RmP52RxOZCGuHU3D7JsfCRZtIXiAU/ZsiEhvQkHuacVFy2H9wCEonLvzEDB7
      I9XOBKTOypkc+zQTPbkgWj3PXIA5fEd5eDNLoELmLlx8jsFGtI1LjSUsOfd/
      p0aWp9RLMPGpjwzyZo/wbP7rgRMwHLma44nDah4zKfQNTaia9TE=
